saas-201-vamsikrishna-bellam/level-07/college_portal/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#index"
  resources :departments, only: [:index, :create, :new]
  resources :sections, only: [:index, :create, :new]
  resources :students, only: [:index,:create, :new, :show]
end

saas-201-vamsikrishna-bellam/level-07/college_portal/app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  def index
    @departments = Department.all
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)

    if @department.save
      redirect_to action: "index"
    else
      flash.now[:danger] = @department.errors.values.join(", ")
      render "new"
    end
  end

  private

  def department_params
    params[:department].permit(:name)
  end
end

saas-201-vamsikrishna-bellam/level-07/college_portal/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    if params[:department_id]
      @sections = Section.where(department_id: params[:department_id]).all
    else
      @sections = Section.all
    end
  end

  def new
    @section = Section.new
    @department_collection = Department.all.collect { |p| [p.name, p.id] }
  end

  def create
    @section = Section.new(section_params)
    @department_collection = Department.all.collect { |p| [p.name, p.id] }
    if @section.save
      redirect_to action: "index"
    else
      flash.now[:danger] = @section.errors.values.join(", ")
      render "new"
    end
  end

  #def show
  # @section=Section.find(params[:id])
  #@students=@section.students
  #end

  private

  def section_params
    params[:section].permit(:name, :department_id)
  end
end

saas-201-vamsikrishna-bellam/level-07/college_portal/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    if params[:section_id]
      @students = Student.where(section_id: params[:section_id]).all
    else
      @students = Student.all
    end
  end

  def new
    @student = Student.new
    @department_collection = Department.all.collect { |p| [p.name, p.id] }
    @section_collection = Section.all.collect { |p| [p.name, p.id] }
  end

  def create
    @student = Student.new(student_params)
    @department_collection = Department.all.collect { |p| [p.name, p.id] }
    @section_collection = Section.all.collect { |p| [p.name, p.id] }

    if @student.save
      redirect_to action: "index"
    else
      flash.now[:danger] = @student.errors.values.join(", ")
      render action: "new"
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  private

  def student_params
    params[:student].permit(:name, :department_id, :section_id, :email)
  end
end

saas-201-vamsikrishna-bellam/level-07/college_portal/app/views/departments/index.html.erb
 <div class="row">
  <div class="col-md-10">
    <h2>Departments</h2>
  </div>
  <div class="col-md-2">
    <a class="btn btn-primary float-right" href="<%= new_department_path %>"  role="button">Create</a>
  </div>
</div>

<br/>

<ul class="list-group">
  <% @departments.each do |department| %>
  <li class="list-group-item"><a href="<%= sections_path(department_id: department.id) %>"><%= department.name %></a></li>
  <% end %>
</ul>

saas-201-vamsikrishna-bellam/level-07/college_portal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Students Portal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%=root_path%>">College Portal</a>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%=root_path%>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= departments_path %>">Departments</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= sections_path %>">Sections</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= students_path %>">Students</a>
      </li>
    </ul>
  </div>
</nav>

    <!-- The yield statement is where views rendered by actions will be inserted. -->
<div class="container">
   <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
  <%= yield %>
</div>

<footer class="page-footer font-small bg-dark">
  <div class="footer-copyright text-center py-3 text-light">(c) 2019 Freshworks:
    <a href="https://freshworks.com"> freshworks.com</a>
  </div>
</footer>
  </body>
</html>

saas-201-vamsikrishna-bellam/level-07/college_portal/app/views/sections/index.html.erb
 <div class="row">
  <div class="col-md-10">
    <h2>Sections</h2>
  </div>
  <div class="col-md-2">
    <a class="btn btn-primary float-right" href="<%= new_section_path %>" role="button">Create</a>
  </div>
</div>

<br/>

<ul class="list-group">
  <% @sections.each do |section| %>
    <li class="list-group-item"><a href="<%= students_path(section_id: section.id) %>">Section  <%= section.name %></li>
  <% end %>
</ul>

saas-201-vamsikrishna-bellam/level-07/college_portal/app/views/students/index.html.erb
 <div class="row">
  <div class="col-md-10">
    <h2>Students</h2>
  </div>
  <div class="col-md-2">
    <a class="btn btn-primary float-right" href="<%= new_student_path %>" role="button">Create</a>
  </div>
</div>

<br/>

<ul class="list-group">
  <% @students.each do |student| %>
    <li class="list-group-item"><%= link_to student.name, student_path(student.id) %></li>
  <% end %>
</ul>